- name: "repository checkout"
  ansible.builtin.git:
    repo: "git@github.com:{{ organization }}/{{ inventory_hostname }}.git"
    # repo: "https://linkorb:{{ github_token }}@github.com/linkorb/{{ inventory_hostname }}.git"
    dest: "{{ cloned_repo_path }}"
    force: true
    depth: 1
# organization variable, useful if the changes in bulk need to be applied to a specific fork instead of the upstream
# linkorb owned repository. During playbook testing useful for auto-push/pull-request scenario testing.

# what next
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html

