- name: create commit
  shell: "git add . && git commit -m 'chore: repo-ansible run'"
  args:
    chdir: "{{ cloned_repo_path }}"

- name: push changes
  command: "git push origin {{ default_branch }}"
  args:
    chdir: "{{ cloned_repo_path }}"
